### ISSUE TITLE
Get rid of the Uri in DisplayRenderer

### ISSUE THREAD

**Issue by raffaeler** [boxofyellow/ConsoleMarkdownRenderer#2]
**Is your feature request related to a problem? Please describe.**
It looks like this library is meant to only render complete markdown contents read by files or network.
Instead, I want to print formatted content on the console "on the fly" as a rich logger.
I would also love to map the markdown formatting to ConsoleColor so that I can format a title in Red instead of `## Title ##` and get rid of the `#` entirely.

**Describe the solution you'd like**
I am trying to use the `Displayer` like this: `Displayer.DisplayMarkdown(content, new Uri("about:blank"));` but I am not sure why I should specify the Uri at all.

**Describe alternatives you've considered**
I don't see any alternatives

**Comment by boxofyellow** [comment]
The `uri` in the versions that you referenced is to denote the base address that should be use for resolving relative links within the document.  So removing it would relative links could no longer be resolved.

That being said a Uri to a local file would likely get the job done, but again that would only work if you ensure relieve links are not in the content you provide.

Providing options to allow mapping the mark down to ConsoleColors would be interesting enhancement.  I'm not sure when I will have time to invest in something like that, but I would be open accepting PRs.

**Comment by boxofyellow** [comment]
@raffaeler so I did have some time, so I created this
- https://github.com/boxofyellow/ConsoleMarkdownRenderer/pull/3

I'll likely merge it soon, but let me know if you had different thoughts.

**Comment by raffaeler** [comment]
Sorry for the delay but I was traveling.

> That being said a Uri to a local file would likely get the job done, but again that would only work if you ensure relieve links are not in the content you provide.

I am aware of this, I think that we have two different use-cases in mind. 
In a classic Console, here you just print messages, the Uri parameter could be at least "about:blank" by default otherwise you have the impression that it won't work unless there is an Uri specified.
In other scenarios, where you want to render a content took by the internet, the Uri must be specified, we all agree on this.

Said that, I would opt for the optional parameters with a default "fake" Uri.

Also, if you can spend time in adding comments, that would help a lot as well.

Thanks

**Comment by raffaeler** [comment]
> @raffaeler so I did have some time, so I created this
> 
> * [Allow caller to overwrite styling #3](https://github.com/boxofyellow/ConsoleMarkdownRenderer/pull/3)
> 
> I'll likely merge it soon, but let me know if you had different thoughts.

Thank you, I commented on the PR directly, well done :)

**Comment by boxofyellow** [comment]
I merged that PR and trigger publishing a new version of the nuget package
https://www.nuget.org/packages/BoxOfYellow.ConsoleMarkdownRenderer/0.6.0
So I think we should be ready to close this one out.

@raffaeler 
Thanks for the suggestion and a reason to revisit an old project

**Comment by boxofyellow** [comment]
I'll think on this one some more

> Said that, I would opt for the optional parameters with a default "fake" Uri.

So lets leave this one open for now.

**Comment by boxofyellow** [comment]
I pushed a change and published a new version that makes the Uri optional, it will just assume that all relative links should be relative to the current working directory.

https://www.nuget.org/packages/BoxOfYellow.ConsoleMarkdownRenderer/0.6.2
